apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: gpu-metrics-exporter
  namespace: monitoring
  labels:
    app: gpu-metrics-exporter
spec:
  selector:
    matchLabels:
      app: gpu-metrics-exporter
  template:
    metadata:
      labels:
       app: gpu-metrics-exporter
      name: gpu-metrics-exporter
    spec:
      nodeSelector:
        hardware-type: NVIDIAGPU
      containers:
      - image: nvidia/pod-gpu-metrics-exporter:v1.0.0-alpha
        name: pod-gpu-metrics-exporter
        securityContext:
          runAsNonRoot: false
          runAsUser: 0
        volumeMounts:
        - name: pod-gpu-resources
          readOnly: true
          mountPath: /var/lib/kubelet/pod-resources
        - name: device-metrics
          readOnly: true
          mountPath: /run/prometheus
      - image: nvidia/dcgm-exporter:1.4.6
        name: nvidia-dcgm-exporter
        securityContext:
          runAsNonRoot: false
          runAsUser: 0
        volumeMounts:
        - name: device-metrics
          mountPath: /run/prometheus
      - image: nginx
        name: nginx
        volumeMounts:
        - name: device-metrics
          mountPath: /usr/share/nginx/html

      volumes:
      - name: pod-gpu-resources
        hostPath:
          path: /var/lib/kubelet/pod-resources
      - name: device-metrics
        emptyDir:
          medium: Memory
